#include "UI/Components/HeapMenu.hpp"

namespace UI::Widgets {

HeapMenu::HeapMenu(AppContext& context)
    : DSAMenuBase(context, "Heap")
{
    updateLayout();
}

std::vector<std::string> HeapMenu::getMainButtonLabels() const {
    // Indices: 0: Create, 1: Insert, 2: Delete Root, 3: Find Maximum, 4: Clear All
    return {"Create", "Insert", "Delete Root", "Find Maximum", "Clear All"};
}

bool HeapMenu::isInstantAction(int index) const {
    // Index 4 maps to the "Clear All" action
    return index == 4;
}

void HeapMenu::setMainButtonEnabled(int index, bool enabled) {
    // Simply call the base class function. 
    // It will handle the mainButtonsEnabled vector AND the grey-out colors.
    DSAMenuBase::setMainButtonEnabled(index, enabled);
}

void HeapMenu::updateLayout() {
    // 1. Let the base class set up initial states
    DSAMenuBase::updateLayout();

    if (mainButtons.empty()) return;

    // 2. Redefine your custom layout
    sf::Vector2f startPos = mainButtons[0].getPosition();
    float btnWidth = 210.f;
    float btnHeight = 45.f;
    float gap = 12.f;

    for (int i = 0; i < (int)mainButtons.size(); ++i) {
        mainButtons[i].setSize({btnWidth, btnHeight});
        mainButtons[i].setPosition({startPos.x + i * (btnWidth + gap), startPos.y});
    }

    // 3. FIX: Re-calculate the sub-menu position based on the NEW button positions
    if (activeMenuIndex >= 0 && activeMenuIndex < (int)mainButtons.size()) {
        sf::Vector2f btnPos = mainButtons[activeMenuIndex].getPosition();
        sf::Vector2f btnSize = mainButtons[activeMenuIndex].getSize();
        
        float newBoxX = btnPos.x;
        float newBoxY = btnPos.y + btnSize.y + 15.f;

        // Clear the old ones generated by the base class call and re-render
        activeSubButtons.clear();
        activeInputs.clear();
        dropdownAction.reset();
        
        renderSubMenu(newBoxX, newBoxY, activeMenuIndex);
    }
}

void HeapMenu::renderSubMenu(float boxX, float boxY, int menuIndex) {
    float gap = 15.f;
    float rowHeight = 55.f;
    float boxHeight = 80.f;
    
    // 1. PRE-CALCULATE WIDTHS
    // We calculate exactly how wide each row is BEFORE placing items 
    // so we can handle screen boundaries and right-alignment correctly.
    float row1Width = 0.f;
    float row2Width = 0.f;

    if (menuIndex == 0) {
        int sel = (lastDropdownIndex >= 0) ? lastDropdownIndex : 0;
        if (sel == 0) { // Random
            // Dropdown(160) + Input(120) + Create(110) + Heapify(120) + 3 gaps
            row1Width = 160.f + gap + 120.f + gap + 110.f + gap + 120.f;
            row2Width = 370.f;
            boxHeight += rowHeight;
        } else { // File
            // Dropdown(160) + Edit(90) + Create(110) + Heapify(120) + 3 gaps
            row1Width = 160.f + gap + 90.f + gap + 110.f + gap + 120.f;
            row2Width = 370.f;
            boxHeight += rowHeight;
        }
    } else if (menuIndex == 1) { // Insert
        row1Width = 140.f + gap + 110.f;
    } else { // Delete, Find, Clear
        row1Width = 110.f;
    }

    // 2. ADJUST boxX FOR SCREEN BOUNDARIES
    float contentMaxWidth = std::max(row1Width, row2Width);
    float finalWidth = contentMaxWidth + 30.f; // 15px padding on each side
    float windowWidth = static_cast<float>(ctx.window.getSize().x);

    if (boxX + finalWidth > windowWidth - 20.f) {
        boxX = windowWidth - finalWidth - 20.f;
    }

    // 3. SET PANEL BACKGROUND
    panelBg.setPosition({boxX, boxY});
    panelBg.setSize({finalWidth, boxHeight});

    // 4. POSITION ANCHORS
    float innerX = boxX + 15.f;
    float currentY = boxY + 15.f;
    float currentX = innerX;
    float row1RightEdge = innerX + row1Width;

    // --- Lambdas ---
    sf::Color innerBtnIdle = Config::UI::Colors::ButtonIdle;

    auto createDropdown = [&](const std::vector<std::string>& options, float x, float w) {
        dropdownAction.emplace(ctx, "Select...", sf::Vector2f{x, currentY}, sf::Vector2f{w, 45.f});
        dropdownAction->setColors(innerBtnIdle, Config::UI::Colors::ButtonHover, Config::UI::Colors::ButtonPressed, sf::Color::White);
        dropdownAction->setOptions(options);
        dropdownAction->setSelectedIndex(std::max(0, lastDropdownIndex));
        dropdownAction->setLabel(dropdownAction->getSelectedText());
        return dropdownAction->getSelectedIndex();
    };

    auto createInput = [&](const std::string& placeholder, float x, float w, InputType type = InputType::AnyText) {
        activeInputs.emplace_back(ctx, sf::Vector2f{x, currentY}, sf::Vector2f{w, 45.f}, "", type);
        activeInputs.back().setPlaceholder(placeholder);
    };

    auto createExecuteBtn = [&](const std::string& label, float x, float w = 110.f) {
        activeSubButtons.emplace_back(ctx, label, sf::Vector2f{x, currentY}, sf::Vector2f{w, 45.f});
        activeSubButtons.back().setColors(innerBtnIdle, Config::UI::Colors::ButtonHover, Config::UI::Colors::ButtonPressed, sf::Color::White);
    };

    // 5. RENDER LOGIC
    if (menuIndex == 0) {
        int sel = createDropdown({"Random", "File"}, currentX, 160.f);
        currentX += 160.f + gap;

        if (sel == 0) { // Random
            createInput("Size", currentX, 120.f, InputType::Integer);
            currentX += 120.f + gap;
            createExecuteBtn("Create", currentX);
            currentX += 110.f + gap;
            createExecuteBtn("Heapify", currentX, 120.f); // Width updated to 120.f
            
            // Row 2: Align Right
            currentY += rowHeight;
            float longBtnWidth = 370.f;
            float row2X = row1RightEdge - longBtnWidth;
            if (row2X < innerX) row2X = innerX;
            createExecuteBtn("Create Pre-Heapified", row2X, longBtnWidth);
        } else { // File
            createExecuteBtn("Edit", currentX, 90.f);
            currentX += 90.f + gap;
            createExecuteBtn("Create", currentX);
            currentX += 110.f + gap;
            createExecuteBtn("Heapify", currentX, 120.f); // Width updated to 120.f
            
            // Row 2: Align Right
            currentY += rowHeight;
            float longBtnWidth = 370.f;
            float row2X = row1RightEdge - longBtnWidth;
            if (row2X < innerX) row2X = innerX;
            createExecuteBtn("Create Pre-Heapified", row2X, longBtnWidth);
        }
    } else if (menuIndex == 1) {
        createInput("Value", currentX, 140.f, InputType::Integer);
        createExecuteBtn("Insert", currentX + 140.f + gap);
    } else {
        createExecuteBtn("Go", currentX);
    }
}

} // namespace UI::Widgets